import { Footer } from '@/components';
import styles from '@/global/styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`main-container ${styles.centered}`}>
        <h1>Index page</h1>
      </main>

      <Footer />
    </div>
  );
}
