import Head from 'next/head';
// eslint-disable-next-line import/extensions
import { Footer } from '@/components';

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="title-xl">
          Super Title (Dark)
        </h1>

        <h1 className="title-xl text-light bg-secondary">
          Super Title (Light)
        </h1>

        <h2 className="title">
          Title
        </h2>

        <h3 className="subtitle">
          Subtitle
        </h3>

        <p className="text-md">
          Button and paragraph text
        </p>

        <p className="text-sm">
          Secondary text
        </p>

        <button className="button button--theme-primary">
          I am a button
        </button>

        <button className="button button--theme-secondary">
          I am a button
        </button>

        <div className="w-25">
          <input
            type="text"
            placeholder="Write your name"
            className="input"
          />
        </div>

        <div className="w-25 input-container">
          <input
            type="text"
            placeholder="Write your name"
            className="input"
          />
          <span className="input__icon">V</span>
        </div>

      </main>

      <Footer />
    </div>
  );
}
